### ISSUE TITLE
TypeError: responder.scrollResponderScrollTo is not a function.

### ISSUE THREAD

**Issue by aamiryameen** [APSL/react-native-keyboard-aware-scroll-view#519]
Hi,
I'm getting this error while run on ios (React Native)

 TypeError: responder.scrollResponderScrollTo is not a function. (In 'responder.scrollResponderScrollTo({
            x: x,
            y: y,
            animated: animated
          })', 'responder.scrollResponderScrollTo' is undefined)

**Comment by dcenatiempo** [comment]
We have this issue as well. We just noticed it after upgrading from RN64 to RN66.

We were on `react-native-keyboard-aware-scroll-view` 0.9.2, but I believe upgrading to 0.9.5 fixes the issue.

What versions of this package and RN are you on?

**Comment by chenop** [comment]
@dcenatiempo Upgrading to 0.9.5 did not solved it for me

**Comment by bisiAlessandroDocPlanner** [comment]
We spotted the problem after updating `react native` to 0.65.2 we fixed it updating the `react-native-keyboard-aware-scroll-view ` to 0.9.5 .  Thank you @dcenatiempo 😄

**Comment by sanjay628** [comment]
Hi I am getting this issue my react native version is "0.66.4" and react-native-keyboard-aware-scroll-view to 0.9.5

**Comment by NaNtrack** [comment]
i've updated the library to 0.9.5 but the issue is still present in react-native 0.65.2, please help!

**Comment by siddharthpvi** [comment]
any update on issue, having same issue.

**Comment by NaNtrack** [comment]
i had the same issue, but it turn out to be the native-base dependency @codler/react-native-keyboard-aware-scroll-view i solved that using https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/504#issuecomment-980236620

**Comment by nandorojo** [comment]
Upgrading to `0.9.5` fixed this for me on RN `0.68`.

**Comment by alexei2000** [comment]
i had the same issue with 0.9.5 and RN 0.68

**Comment by tosifkhan01** [comment]
Facing same issue on "react-native": "0.66.4" and "react-native-keyboard-aware-scroll-view": "0.9.5"

**Comment by harshmdr** [comment]
Facing same issue on "RN:0.68.2" and "native base:2.15.2"

**Comment by H4mxa** [comment]
Any update on this issue?

**Comment by harshmdr** [comment]
"resolutions": {
    "**/native-base/@codler/react-native-keyboard-aware-scroll-view": "2.0.1"
  },
  It works if you are using native base v2

**Comment by davidwinograd1** [comment]
Any solution? I tried every solution in this thread and nothing works. Upgrading to 0.9.5 did not fix it either. I'm on RN 68. @H4mxa @tosifkhan01 @alexei2000

**Comment by Mihai-github** [comment]
+1

**Comment by VladyslavForm** [comment]
+1, RN 0.70

**Comment by DoHue97** [comment]
Hello all, any update for this issue? 
still error with react-native: 0.66.3 and 0.9.5 :(((

**Comment by formaliuk** [comment]
It seems like an issue with some relational dependencies, they fixed this issue in newer versions, so you can bump all the major versions of your packages and it should help.

**Comment by DoHue97** [comment]
> It seems like an issue with some relational dependencies, they fixed this issue in newer versions, so you can bump all the major versions of your packages and it should help.

my native base is 2.15.2, i saw the package.json of this is "@codler/react-native-keyboard-aware-scroll-view": "1.0.1". Do you have any suggest ?
![image](https://github.com/user-attachments/assets/1ce1113a-3de0-4364-80dc-4e7996f668c6)

**Comment by formaliuk** [comment]
You should update your native base version to a new one. This issue is with their 2nd major (2.x.x), update it to the 3.x.x.

**Comment by DoHue97** [comment]
![image](https://github.com/user-attachments/assets/9cef37ef-95a4-42f9-8b2b-dda48276a953)
i tried to add resolutions but doent work :(
"resolutions": {
    "@codler/react-native-keyboard-aware-scroll-view": "2.0.0"
  },

**Comment by formaliuk** [comment]
All other options to deal with this issue didn't help me. Only major update worked.

**Comment by DoHue97** [comment]
> All other options to deal with this issue didn't help me. Only major update worked.

haiza, this isn't not good solution, because my code will change more, but thank for your help!

**Comment by formaliuk** [comment]
That's how it is, you'll need to fix a lot after major update.
